new error when old one is fixed
Error: XMLHttpRequest cannot load
http://clementhamon.com/IDP/public/event/1/attendees. A wildcard '*'
cannot be used in the 'Access-Control-Allow-Origin' header when the
credentials flag is true. Origin 'http://localhost:9000' is therefore
not allowed access. The credentials mode of an XMLHttpRequest is
controlled by the withCredentials attribute.